import type { EndpointDefinition, EndpointGroup, EndpointAuthMode, HttpMethod } from "@/types/domain";

const jwt: EndpointAuthMode = "jwt";
const publicApi: EndpointAuthMode = "public";

function endpoint(config: {
  id: string;
  title: string;
  description: string;
  method: HttpMethod;
  path: string;
  auth: EndpointAuthMode;
  notes?: string;
  pathParams?: EndpointDefinition["pathParams"];
  queryTemplate?: Record<string, unknown>;
  bodyTemplate?: unknown;
}): EndpointDefinition {
  return config;
}

export const endpointGroups: EndpointGroup[] = [
  {
    id: "auth",
    title: "1. Autenticacion",
    description: "Comienza aqui. `register` o `login` deben guardar JWT para las demas tarjetas.",
    endpoints: [
      endpoint({
        id: "auth.register",
        title: "Registrar usuario",
        description: "Crea una cuenta y devuelve `accessToken` y `refreshToken`.",
        method: "POST",
        path: "/auth/register",
        auth: publicApi,
        bodyTemplate: {
          email: "demo@appfoodspring.com",
          password: "Password123!",
          firstName: "Demo",
          lastName: "Tester",
        },
      }),
      endpoint({
        id: "auth.login",
        title: "Iniciar sesion",
        description: "Obtiene JWT para ejecutar el resto de endpoints protegidos.",
        method: "POST",
        path: "/auth/login",
        auth: publicApi,
        bodyTemplate: {
          email: "demo@appfoodspring.com",
          password: "Password123!",
        },
      }),
      endpoint({
        id: "auth.refresh-token",
        title: "Renovar access token",
        description: "Usa el `refreshToken` activo o edita el payload manualmente.",
        method: "POST",
        path: "/auth/refresh-token",
        auth: publicApi,
        bodyTemplate: {
          refreshToken: "SE_RELLENA_AUTOMATICAMENTE_SI_LO_DEJAS_VACIO",
        },
      }),
      endpoint({
        id: "auth.me",
        title: "Perfil autenticado",
        description: "Verifica que el JWT actual sea valido.",
        method: "GET",
        path: "/auth/me",
        auth: jwt,
      }),
      endpoint({
        id: "auth.logout",
        title: "Cerrar sesion",
        description: "Invalidar la sesion actual en backend y limpiar tokens locales.",
        method: "POST",
        path: "/auth/logout",
        auth: jwt,
      }),
    ],
  },
  {
    id: "profile",
    title: "2. Perfil y onboarding",
    description: "Despues del login conviene completar perfil y objetivos para que planes y analisis tengan contexto.",
    endpoints: [
      endpoint({
        id: "users.me.get",
        title: "Obtener mi usuario",
        description: "Retorna email, estado y perfil actual.",
        method: "GET",
        path: "/users/me",
        auth: jwt,
      }),
      endpoint({
        id: "users.me.patch",
        title: "Actualizar mi perfil",
        description: "Completa datos fisicos y metas base.",
        method: "PATCH",
        path: "/users/me",
        auth: jwt,
        bodyTemplate: {
          firstName: "Demo",
          lastName: "Tester",
          age: 29,
          gender: "female",
          weightKg: 68.5,
          heightCm: 170,
          activityLevel: "moderate",
          goal: "fat_loss",
          targetWeightKg: 63,
          dailyCalorieGoal: 2100,
          dailyProteinGoal: 130,
          dailyCarbsGoal: 220,
          dailyFatGoal: 60,
        },
      }),
      endpoint({
        id: "users.me.stats",
        title: "Ver mis estadisticas",
        description: "Conteos agregados por modulo del usuario actual.",
        method: "GET",
        path: "/users/me/stats",
        auth: jwt,
      }),
      endpoint({
        id: "onboarding.create",
        title: "Crear onboarding",
        description: "Questionario inicial para metas, restricciones y preferencias.",
        method: "POST",
        path: "/onboarding",
        auth: jwt,
        bodyTemplate: {
          mainGoal: "gain_muscle",
          currentWeightKg: 68.5,
          targetWeightKg: 72,
          heightCm: 170,
          age: 29,
          gender: "female",
          activityLevel: "moderate",
          trainingDaysPerWeek: 4,
          dietType: "balanced",
          foodRestrictions: "none",
          allergies: "none",
          preferredFoods: "pollo, arroz, yogur",
          dislikedFoods: "higado",
          healthNotes: "sin observaciones",
        },
      }),
      endpoint({
        id: "onboarding.me.get",
        title: "Leer onboarding",
        description: "Recupera el cuestionario guardado del usuario actual.",
        method: "GET",
        path: "/onboarding/me",
        auth: jwt,
      }),
      endpoint({
        id: "onboarding.me.patch",
        title: "Actualizar onboarding",
        description: "Ajusta respuestas del cuestionario sin rehacer el registro.",
        method: "PATCH",
        path: "/onboarding/me",
        auth: jwt,
        bodyTemplate: {
          mainGoal: "maintenance",
          activityLevel: "high",
          trainingDaysPerWeek: 5,
          preferredFoods: "salmon, avena, huevo",
        },
      }),
      endpoint({
        id: "onboarding.calculate-goals",
        title: "Calcular metas",
        description: "Devuelve recomendacion de calorias y macros.",
        method: "POST",
        path: "/onboarding/calculate-goals",
        auth: jwt,
        bodyTemplate: {
          weightKg: 68.5,
          targetWeightKg: 72,
          heightCm: 170,
          age: 29,
          gender: "female",
          activityLevel: "moderate",
          mainGoal: "gain_muscle",
        },
      }),
    ],
  },
  {
    id: "catalog",
    title: "3. Catalogos base",
    description: "Carga alimentos y ejercicios antes de enlazarlos con recetas, refri, logs y entrenamientos.",
    endpoints: [
      endpoint({
        id: "foods.list",
        title: "Listar alimentos",
        description: "Catálogo principal de alimentos.",
        method: "GET",
        path: "/foods",
        auth: jwt,
      }),
      endpoint({
        id: "foods.search",
        title: "Buscar alimentos",
        description: "Busqueda textual para elegir IDs reutilizables.",
        method: "GET",
        path: "/foods/search",
        auth: jwt,
        queryTemplate: {
          query: "banana",
        },
      }),
      endpoint({
        id: "foods.get",
        title: "Obtener alimento por ID",
        description: "Consulta un alimento puntual.",
        method: "GET",
        path: "/foods/{id}",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_FOOD_ID", required: true }],
      }),
      endpoint({
        id: "foods.category",
        title: "Filtrar alimentos por categoria",
        description: "Revisa la taxonomia cargada.",
        method: "GET",
        path: "/foods/category/{category}",
        auth: jwt,
        pathParams: [{ name: "category", value: "fruits", required: true }],
      }),
      endpoint({
        id: "foods.barcode",
        title: "Buscar alimento por codigo",
        description: "Consulta por barcode cuando exista.",
        method: "GET",
        path: "/foods/barcode/{barcode}",
        auth: jwt,
        pathParams: [{ name: "barcode", value: "7501031311309", required: true }],
      }),
      endpoint({
        id: "foods.create",
        title: "Crear alimento",
        description: "Alta manual de alimento completo.",
        method: "POST",
        path: "/foods",
        auth: jwt,
        bodyTemplate: {
          name: "Greek Yogurt",
          brand: "Demo Foods",
          category: "dairy",
          servingSize: 100,
          servingUnit: "g",
          caloriesPer100g: 97,
          proteinPer100g: 10,
          carbsPer100g: 3.6,
          fatPer100g: 4.2,
          fiberPer100g: 0,
          sugarPer100g: 3.2,
          sodiumPer100g: 36,
          barcode: "1234567890123",
          externalSource: "manual",
        },
      }),
      endpoint({
        id: "foods.custom",
        title: "Crear alimento custom",
        description: "Alta rapida sin tantos campos obligatorios.",
        method: "POST",
        path: "/foods/custom",
        auth: jwt,
        bodyTemplate: {
          name: "Batido casero",
          brand: "Casa",
          category: "beverage",
          servingSize: 350,
          servingUnit: "ml",
          caloriesPer100g: 80,
          proteinPer100g: 6,
          carbsPer100g: 9,
          fatPer100g: 2,
          fiberPer100g: 1,
          sugarPer100g: 7,
          sodiumPer100g: 45,
        },
      }),
      endpoint({
        id: "foods.patch",
        title: "Actualizar alimento",
        description: "Edita un alimento existente.",
        method: "PATCH",
        path: "/foods/{id}",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_FOOD_ID", required: true }],
        bodyTemplate: {
          name: "Greek Yogurt Natural",
          category: "dairy",
          caloriesPer100g: 95,
        },
      }),
      endpoint({
        id: "foods.delete",
        title: "Eliminar alimento",
        description: "Borra un alimento por UUID.",
        method: "DELETE",
        path: "/foods/{id}",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_FOOD_ID", required: true }],
      }),
      endpoint({
        id: "exercises.list",
        title: "Listar ejercicios",
        description: "Catálogo general de ejercicios.",
        method: "GET",
        path: "/exercises",
        auth: jwt,
      }),
      endpoint({
        id: "exercises.search",
        title: "Buscar ejercicios",
        description: "Busqueda textual de ejercicios.",
        method: "GET",
        path: "/exercises/search",
        auth: jwt,
        queryTemplate: {
          query: "squat",
        },
      }),
      endpoint({
        id: "exercises.muscle-group",
        title: "Filtrar por grupo muscular",
        description: "Consulta rapida por grupo muscular.",
        method: "GET",
        path: "/exercises/muscle-group/{muscleGroup}",
        auth: jwt,
        pathParams: [{ name: "muscleGroup", value: "legs", required: true }],
      }),
      endpoint({
        id: "exercises.get",
        title: "Obtener ejercicio por ID",
        description: "Detalle individual del ejercicio.",
        method: "GET",
        path: "/exercises/{id}",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_EXERCISE_ID", required: true }],
      }),
      endpoint({
        id: "exercises.create",
        title: "Crear ejercicio",
        description: "Alta manual de ejercicio.",
        method: "POST",
        path: "/exercises",
        auth: jwt,
        bodyTemplate: {
          name: "Bulgarian Split Squat",
          muscleGroup: "legs",
          equipment: "dumbbells",
          difficulty: "intermediate",
          description: "Trabajo unilateral para cuadriceps y gluteo.",
          recommendedSets: 4,
          recommendedReps: "8-12",
          recommendedTimeSeconds: 60,
        },
      }),
      endpoint({
        id: "exercises.patch",
        title: "Actualizar ejercicio",
        description: "Edita el ejercicio por UUID.",
        method: "PATCH",
        path: "/exercises/{id}",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_EXERCISE_ID", required: true }],
        bodyTemplate: {
          name: "Bulgarian Split Squat",
          difficulty: "advanced",
          recommendedSets: 5,
        },
      }),
      endpoint({
        id: "exercises.delete",
        title: "Eliminar ejercicio",
        description: "Borra un ejercicio por UUID.",
        method: "DELETE",
        path: "/exercises/{id}",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_EXERCISE_ID", required: true }],
      }),
    ],
  },
  {
    id: "recipes",
    title: "4. Recetas y comunidad",
    description: "Crea recetas una vez que ya existan alimentos. Luego puedes publicarlas como posts.",
    endpoints: [
      endpoint({
        id: "recipes.create",
        title: "Crear receta",
        description: "Alta base de receta sin ingredientes.",
        method: "POST",
        path: "/recipes",
        auth: jwt,
        bodyTemplate: {
          title: "Bowl proteico",
          description: "Comida rapida post entrenamiento.",
          instructions: "Mezcla todos los ingredientes y sirve.",
          prepTimeMinutes: 10,
          cookTimeMinutes: 5,
          servings: 1,
          isPublic: true,
          isAiGenerated: false,
          isHighCalorie: false,
          isHighProtein: true,
          isLowCarb: false,
        },
      }),
      endpoint({
        id: "recipes.list",
        title: "Listar recetas",
        description: "Consulta general de recetas accesibles.",
        method: "GET",
        path: "/recipes",
        auth: jwt,
      }),
      endpoint({
        id: "recipes.public",
        title: "Listar recetas publicas",
        description: "Vista publica pensada para explorar comunidad.",
        method: "GET",
        path: "/recipes/public",
        auth: jwt,
      }),
      endpoint({
        id: "recipes.mine",
        title: "Listar mis recetas",
        description: "Recetas creadas por el usuario autenticado.",
        method: "GET",
        path: "/recipes/me",
        auth: jwt,
      }),
      endpoint({
        id: "recipes.get",
        title: "Obtener receta por ID",
        description: "Detalle de receta individual.",
        method: "GET",
        path: "/recipes/{id}",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_RECIPE_ID", required: true }],
      }),
      endpoint({
        id: "recipes.patch",
        title: "Actualizar receta",
        description: "Edita metadatos de la receta.",
        method: "PATCH",
        path: "/recipes/{id}",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_RECIPE_ID", required: true }],
        bodyTemplate: {
          title: "Bowl proteico deluxe",
          description: "Version ajustada con mas proteina.",
          instructions: "Cocina, mezcla y sirve.",
          prepTimeMinutes: 12,
          cookTimeMinutes: 7,
          servings: 1,
          isPublic: true,
          isAiGenerated: false,
          isHighCalorie: false,
          isHighProtein: true,
          isLowCarb: false,
        },
      }),
      endpoint({
        id: "recipes.delete",
        title: "Eliminar receta",
        description: "Borra una receta completa.",
        method: "DELETE",
        path: "/recipes/{id}",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_RECIPE_ID", required: true }],
      }),
      endpoint({
        id: "recipes.ingredients.add",
        title: "Agregar ingrediente a receta",
        description: "Necesita `foodId` valido del catalogo.",
        method: "POST",
        path: "/recipes/{id}/ingredients",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_RECIPE_ID", required: true }],
        bodyTemplate: {
          foodId: "REEMPLAZAR_FOOD_ID",
          quantity: 150,
          unit: "g",
          calories: 120,
          proteinG: 18,
          carbsG: 8,
          fatG: 2,
        },
      }),
      endpoint({
        id: "recipes.ingredients.patch",
        title: "Actualizar ingrediente de receta",
        description: "Edita una linea de ingrediente por UUID.",
        method: "PATCH",
        path: "/recipes/{id}/ingredients/{ingredientId}",
        auth: jwt,
        pathParams: [
          { name: "id", value: "REEMPLAZAR_RECIPE_ID", required: true },
          { name: "ingredientId", value: "REEMPLAZAR_INGREDIENT_ID", required: true },
        ],
        bodyTemplate: {
          foodId: "REEMPLAZAR_FOOD_ID",
          quantity: 180,
          unit: "g",
          calories: 144,
          proteinG: 22,
          carbsG: 10,
          fatG: 2,
        },
      }),
      endpoint({
        id: "recipes.ingredients.delete",
        title: "Eliminar ingrediente de receta",
        description: "Borra una linea de ingrediente.",
        method: "DELETE",
        path: "/recipes/{id}/ingredients/{ingredientId}",
        auth: jwt,
        pathParams: [
          { name: "id", value: "REEMPLAZAR_RECIPE_ID", required: true },
          { name: "ingredientId", value: "REEMPLAZAR_INGREDIENT_ID", required: true },
        ],
      }),
      endpoint({
        id: "recipes.calculate-nutrition",
        title: "Recalcular nutricion",
        description: "Fuerza recalculo de macros de la receta.",
        method: "POST",
        path: "/recipes/{id}/calculate-nutrition",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_RECIPE_ID", required: true }],
      }),
      endpoint({
        id: "recipe-posts.create",
        title: "Crear post de receta",
        description: "Publica una receta en formato social.",
        method: "POST",
        path: "/recipe-posts",
        auth: jwt,
        bodyTemplate: {
          recipeId: "REEMPLAZAR_RECIPE_ID",
          title: "Mi receta favorita",
          content: "Ideal para despues de entrenar.",
        },
      }),
      endpoint({
        id: "recipe-posts.list",
        title: "Listar posts",
        description: "Timeline actual de publicaciones.",
        method: "GET",
        path: "/recipe-posts",
        auth: jwt,
      }),
      endpoint({
        id: "recipe-posts.get",
        title: "Obtener post por ID",
        description: "Detalle de un post concreto.",
        method: "GET",
        path: "/recipe-posts/{id}",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_POST_ID", required: true }],
      }),
      endpoint({
        id: "recipe-posts.patch",
        title: "Actualizar post",
        description: "Edita el titulo o contenido del post.",
        method: "PATCH",
        path: "/recipe-posts/{id}",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_POST_ID", required: true }],
        bodyTemplate: {
          recipeId: "REEMPLAZAR_RECIPE_ID",
          title: "Mi receta favorita actualizada",
          content: "Ahora con ingredientes mejor balanceados.",
        },
      }),
      endpoint({
        id: "recipe-posts.delete",
        title: "Eliminar post",
        description: "Borra la publicacion del usuario.",
        method: "DELETE",
        path: "/recipe-posts/{id}",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_POST_ID", required: true }],
      }),
      endpoint({
        id: "recipe-posts.like",
        title: "Dar like a post",
        description: "Marca me gusta al post indicado.",
        method: "POST",
        path: "/recipe-posts/{id}/like",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_POST_ID", required: true }],
      }),
      endpoint({
        id: "recipe-posts.unlike",
        title: "Quitar like de post",
        description: "Revierte el me gusta previo.",
        method: "DELETE",
        path: "/recipe-posts/{id}/like",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_POST_ID", required: true }],
      }),
    ],
  },
  {
    id: "tracking",
    title: "5. Seguimiento diario",
    description: "Con foods y recipes listos, ya puedes registrar comida, refri y notas diarias.",
    endpoints: [
      endpoint({
        id: "daily-notes.create",
        title: "Crear nota diaria",
        description: "Registro rapido de estado general del dia.",
        method: "POST",
        path: "/daily-notes",
        auth: jwt,
        bodyTemplate: {
          noteDate: "2026-06-01",
          mood: "focused",
          energyLevel: 8,
          sleepHours: 7.5,
          content: "Buen dia de entrenamiento y comidas ordenadas.",
        },
      }),
      endpoint({
        id: "daily-notes.list",
        title: "Listar notas por fecha",
        description: "Obtiene notas del dia indicado.",
        method: "GET",
        path: "/daily-notes",
        auth: jwt,
        queryTemplate: {
          date: "2026-06-01",
        },
      }),
      endpoint({
        id: "daily-notes.range",
        title: "Listar notas por rango",
        description: "Consulta historica por rango de fechas.",
        method: "GET",
        path: "/daily-notes/range",
        auth: jwt,
        queryTemplate: {
          startDate: "2026-05-26",
          endDate: "2026-06-01",
        },
      }),
      endpoint({
        id: "daily-notes.get",
        title: "Obtener nota por ID",
        description: "Detalle de una nota puntual.",
        method: "GET",
        path: "/daily-notes/{id}",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_NOTE_ID", required: true }],
      }),
      endpoint({
        id: "daily-notes.patch",
        title: "Actualizar nota diaria",
        description: "Ajusta mood, energia o contenido.",
        method: "PATCH",
        path: "/daily-notes/{id}",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_NOTE_ID", required: true }],
        bodyTemplate: {
          noteDate: "2026-06-01",
          mood: "recovered",
          energyLevel: 9,
          sleepHours: 8,
          content: "Recuperacion mucho mejor que ayer.",
        },
      }),
      endpoint({
        id: "daily-notes.delete",
        title: "Eliminar nota diaria",
        description: "Borra una nota del usuario.",
        method: "DELETE",
        path: "/daily-notes/{id}",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_NOTE_ID", required: true }],
      }),
      endpoint({
        id: "food-logs.create",
        title: "Crear food log",
        description: "Registra un alimento consumido en una fecha.",
        method: "POST",
        path: "/food-logs",
        auth: jwt,
        bodyTemplate: {
          foodId: "REEMPLAZAR_FOOD_ID",
          logDate: "2026-06-01",
          mealType: "breakfast",
          quantity: 120,
          unit: "g",
          calories: 140,
          proteinG: 8,
          carbsG: 16,
          fatG: 4,
        },
      }),
      endpoint({
        id: "food-logs.list",
        title: "Listar food logs por fecha",
        description: "Consulta registros del dia.",
        method: "GET",
        path: "/food-logs",
        auth: jwt,
        queryTemplate: {
          date: "2026-06-01",
        },
      }),
      endpoint({
        id: "food-logs.range",
        title: "Listar food logs por rango",
        description: "Consulta historica de consumo.",
        method: "GET",
        path: "/food-logs/range",
        auth: jwt,
        queryTemplate: {
          startDate: "2026-05-26",
          endDate: "2026-06-01",
        },
      }),
      endpoint({
        id: "food-logs.summary",
        title: "Resumen diario de food logs",
        description: "Totales de macros y lista de items del dia.",
        method: "GET",
        path: "/food-logs/summary",
        auth: jwt,
        queryTemplate: {
          date: "2026-06-01",
        },
      }),
      endpoint({
        id: "food-logs.patch",
        title: "Actualizar food log",
        description: "Edita un registro ya guardado.",
        method: "PATCH",
        path: "/food-logs/{id}",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_FOOD_LOG_ID", required: true }],
        bodyTemplate: {
          foodId: "REEMPLAZAR_FOOD_ID",
          logDate: "2026-06-01",
          mealType: "lunch",
          quantity: 180,
          unit: "g",
          calories: 220,
          proteinG: 14,
          carbsG: 28,
          fatG: 6,
        },
      }),
      endpoint({
        id: "food-logs.delete",
        title: "Eliminar food log",
        description: "Borra un registro del diario alimenticio.",
        method: "DELETE",
        path: "/food-logs/{id}",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_FOOD_LOG_ID", required: true }],
      }),
      endpoint({
        id: "fridge.create",
        title: "Agregar item al refri",
        description: "Relaciona un alimento con cantidad y caducidad.",
        method: "POST",
        path: "/fridge/items",
        auth: jwt,
        bodyTemplate: {
          foodId: "REEMPLAZAR_FOOD_ID",
          quantity: 500,
          unit: "g",
          expirationDate: "2026-06-06",
        },
      }),
      endpoint({
        id: "fridge.list",
        title: "Listar items del refri",
        description: "Inventario actual del usuario.",
        method: "GET",
        path: "/fridge/items",
        auth: jwt,
      }),
      endpoint({
        id: "fridge.patch",
        title: "Actualizar item del refri",
        description: "Ajusta cantidad o fecha de caducidad.",
        method: "PATCH",
        path: "/fridge/items/{id}",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_FRIDGE_ITEM_ID", required: true }],
        bodyTemplate: {
          foodId: "REEMPLAZAR_FOOD_ID",
          quantity: 350,
          unit: "g",
          expirationDate: "2026-06-04",
        },
      }),
      endpoint({
        id: "fridge.delete",
        title: "Eliminar item del refri",
        description: "Borra un item del inventario.",
        method: "DELETE",
        path: "/fridge/items/{id}",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_FRIDGE_ITEM_ID", required: true }],
      }),
      endpoint({
        id: "fridge.match-recipes",
        title: "Buscar recetas compatibles con refri",
        description: "Cruza inventario actual con ingredientes de recetas.",
        method: "POST",
        path: "/fridge/match-recipes",
        auth: jwt,
      }),
    ],
  },
  {
    id: "meal-plans",
    title: "6. Planes de comida",
    description: "Usa onboarding y recetas para crear planes, dias, comidas y analisis.",
    endpoints: [
      endpoint({
        id: "meal-plans.create",
        title: "Crear meal plan",
        description: "Alta base del plan semanal o mensual.",
        method: "POST",
        path: "/meal-plans",
        auth: jwt,
        bodyTemplate: {
          title: "Plan definicion junio",
          description: "Plan semanal moderado en calorias.",
          startDate: "2026-06-01",
          endDate: "2026-06-07",
          dailyCalorieTarget: 2100,
          isAiGenerated: false,
        },
      }),
      endpoint({
        id: "meal-plans.mine",
        title: "Listar mis meal plans",
        description: "Consulta los planes del usuario actual.",
        method: "GET",
        path: "/meal-plans/me",
        auth: jwt,
      }),
      endpoint({
        id: "meal-plans.get",
        title: "Obtener meal plan por ID",
        description: "Detalle puntual de un plan.",
        method: "GET",
        path: "/meal-plans/{id}",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_MEAL_PLAN_ID", required: true }],
      }),
      endpoint({
        id: "meal-plans.patch",
        title: "Actualizar meal plan",
        description: "Edita rango y objetivo calorico.",
        method: "PATCH",
        path: "/meal-plans/{id}",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_MEAL_PLAN_ID", required: true }],
        bodyTemplate: {
          title: "Plan definicion junio ajustado",
          description: "Ajuste despues de primera revision.",
          startDate: "2026-06-01",
          endDate: "2026-06-08",
          dailyCalorieTarget: 2050,
          isAiGenerated: false,
        },
      }),
      endpoint({
        id: "meal-plans.delete",
        title: "Eliminar meal plan",
        description: "Borra el plan completo.",
        method: "DELETE",
        path: "/meal-plans/{id}",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_MEAL_PLAN_ID", required: true }],
      }),
      endpoint({
        id: "meal-plans.days.create",
        title: "Agregar dia a meal plan",
        description: "Crea una jornada dentro del plan.",
        method: "POST",
        path: "/meal-plans/{id}/days",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_MEAL_PLAN_ID", required: true }],
        bodyTemplate: {
          dayNumber: 1,
          dayDate: "2026-06-01",
          totalCalories: 0,
          totalProteinG: 0,
          totalCarbsG: 0,
          totalFatG: 0,
        },
      }),
      endpoint({
        id: "meal-plans.days.list",
        title: "Listar dias de meal plan",
        description: "Obtiene dias y comidas del plan.",
        method: "GET",
        path: "/meal-plans/{id}/days",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_MEAL_PLAN_ID", required: true }],
      }),
      endpoint({
        id: "meal-plan-days.patch",
        title: "Actualizar dia de meal plan",
        description: "Edita fecha o acumulados del dia.",
        method: "PATCH",
        path: "/meal-plan-days/{dayId}",
        auth: jwt,
        pathParams: [{ name: "dayId", value: "REEMPLAZAR_MEAL_PLAN_DAY_ID", required: true }],
        bodyTemplate: {
          dayNumber: 1,
          dayDate: "2026-06-01",
          totalCalories: 1950,
          totalProteinG: 132,
          totalCarbsG: 210,
          totalFatG: 55,
        },
      }),
      endpoint({
        id: "meal-plan-days.delete",
        title: "Eliminar dia de meal plan",
        description: "Borra una jornada del plan.",
        method: "DELETE",
        path: "/meal-plan-days/{dayId}",
        auth: jwt,
        pathParams: [{ name: "dayId", value: "REEMPLAZAR_MEAL_PLAN_DAY_ID", required: true }],
      }),
      endpoint({
        id: "meal-plan-days.meals.create",
        title: "Agregar comida a dia",
        description: "Relaciona receta o alimento con una comida del plan.",
        method: "POST",
        path: "/meal-plan-days/{dayId}/meals",
        auth: jwt,
        pathParams: [{ name: "dayId", value: "REEMPLAZAR_MEAL_PLAN_DAY_ID", required: true }],
        bodyTemplate: {
          mealType: "breakfast",
          recipeId: "REEMPLAZAR_RECIPE_ID",
          foodId: null,
          quantity: 1,
          notes: "Porcion completa",
          calories: 450,
          proteinG: 32,
          carbsG: 40,
          fatG: 12,
        },
      }),
      endpoint({
        id: "meal-plan-meals.patch",
        title: "Actualizar comida de meal plan",
        description: "Edita una comida ya agregada.",
        method: "PATCH",
        path: "/meal-plan-meals/{mealId}",
        auth: jwt,
        pathParams: [{ name: "mealId", value: "REEMPLAZAR_MEAL_PLAN_MEAL_ID", required: true }],
        bodyTemplate: {
          mealType: "lunch",
          recipeId: "REEMPLAZAR_RECIPE_ID",
          foodId: null,
          quantity: 1,
          notes: "Ajustado para mas saciedad",
          calories: 520,
          proteinG: 35,
          carbsG: 48,
          fatG: 14,
        },
      }),
      endpoint({
        id: "meal-plan-meals.delete",
        title: "Eliminar comida de meal plan",
        description: "Borra una linea de comida del plan.",
        method: "DELETE",
        path: "/meal-plan-meals/{mealId}",
        auth: jwt,
        pathParams: [{ name: "mealId", value: "REEMPLAZAR_MEAL_PLAN_MEAL_ID", required: true }],
      }),
      endpoint({
        id: "meal-plans.analyze",
        title: "Analizar meal plan",
        description: "Evalua calorias y proteina frente al objetivo del usuario.",
        method: "POST",
        path: "/meal-plans/{id}/analyze",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_MEAL_PLAN_ID", required: true }],
      }),
    ],
  },
  {
    id: "workouts",
    title: "7. Entrenamiento",
    description: "Primero crea o revisa ejercicios, luego arma planes y finalmente registra ejecuciones.",
    endpoints: [
      endpoint({
        id: "workout-plans.create",
        title: "Crear workout plan",
        description: "Alta base del plan de entrenamiento.",
        method: "POST",
        path: "/workout-plans",
        auth: jwt,
        bodyTemplate: {
          title: "Push Pull Legs",
          description: "Rutina de hipertrofia 3 dias.",
          goal: "gain_muscle",
          daysPerWeek: 3,
          isAiGenerated: false,
        },
      }),
      endpoint({
        id: "workout-plans.mine",
        title: "Listar mis workout plans",
        description: "Consulta los planes del usuario actual.",
        method: "GET",
        path: "/workout-plans/me",
        auth: jwt,
      }),
      endpoint({
        id: "workout-plans.get",
        title: "Obtener workout plan por ID",
        description: "Detalle puntual del plan.",
        method: "GET",
        path: "/workout-plans/{id}",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_WORKOUT_PLAN_ID", required: true }],
      }),
      endpoint({
        id: "workout-plans.patch",
        title: "Actualizar workout plan",
        description: "Edita descripcion, goal o frecuencia.",
        method: "PATCH",
        path: "/workout-plans/{id}",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_WORKOUT_PLAN_ID", required: true }],
        bodyTemplate: {
          title: "Push Pull Legs Plus",
          description: "Version ajustada con cuarto dia opcional.",
          goal: "gain_muscle",
          daysPerWeek: 4,
          isAiGenerated: false,
        },
      }),
      endpoint({
        id: "workout-plans.delete",
        title: "Eliminar workout plan",
        description: "Borra el plan completo.",
        method: "DELETE",
        path: "/workout-plans/{id}",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_WORKOUT_PLAN_ID", required: true }],
      }),
      endpoint({
        id: "workout-plans.days.create",
        title: "Agregar dia a workout plan",
        description: "Crea una jornada del plan.",
        method: "POST",
        path: "/workout-plans/{id}/days",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_WORKOUT_PLAN_ID", required: true }],
        bodyTemplate: {
          dayNumber: 1,
          title: "Push",
          focusArea: "chest_shoulders_triceps",
        },
      }),
      endpoint({
        id: "workout-plans.days.list",
        title: "Listar dias de workout plan",
        description: "Obtiene dias y ejercicios del plan.",
        method: "GET",
        path: "/workout-plans/{id}/days",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_WORKOUT_PLAN_ID", required: true }],
      }),
      endpoint({
        id: "workout-plan-days.patch",
        title: "Actualizar dia de workout plan",
        description: "Edita titulo o foco del dia.",
        method: "PATCH",
        path: "/workout-plan-days/{dayId}",
        auth: jwt,
        pathParams: [{ name: "dayId", value: "REEMPLAZAR_WORKOUT_PLAN_DAY_ID", required: true }],
        bodyTemplate: {
          dayNumber: 1,
          title: "Push pesado",
          focusArea: "chest_shoulders_triceps",
        },
      }),
      endpoint({
        id: "workout-plan-days.delete",
        title: "Eliminar dia de workout plan",
        description: "Borra una jornada del plan.",
        method: "DELETE",
        path: "/workout-plan-days/{dayId}",
        auth: jwt,
        pathParams: [{ name: "dayId", value: "REEMPLAZAR_WORKOUT_PLAN_DAY_ID", required: true }],
      }),
      endpoint({
        id: "workout-plan-days.exercises.create",
        title: "Agregar ejercicio a dia",
        description: "Relaciona un ejercicio del catalogo con el dia del plan.",
        method: "POST",
        path: "/workout-plan-days/{dayId}/exercises",
        auth: jwt,
        pathParams: [{ name: "dayId", value: "REEMPLAZAR_WORKOUT_PLAN_DAY_ID", required: true }],
        bodyTemplate: {
          exerciseId: "REEMPLAZAR_EXERCISE_ID",
          sets: 4,
          reps: "8-10",
          weightKg: 20,
          durationSeconds: 60,
          restSeconds: 90,
          notes: "Controlar tecnica",
        },
      }),
      endpoint({
        id: "workout-plan-exercises.patch",
        title: "Actualizar ejercicio de plan",
        description: "Edita volumen o notas del ejercicio asignado.",
        method: "PATCH",
        path: "/workout-plan-exercises/{id}",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_WORKOUT_PLAN_EXERCISE_ID", required: true }],
        bodyTemplate: {
          exerciseId: "REEMPLAZAR_EXERCISE_ID",
          sets: 5,
          reps: "6-8",
          weightKg: 22.5,
          durationSeconds: 70,
          restSeconds: 120,
          notes: "Subir carga progresivamente",
        },
      }),
      endpoint({
        id: "workout-plan-exercises.delete",
        title: "Eliminar ejercicio de plan",
        description: "Borra la asignacion del ejercicio.",
        method: "DELETE",
        path: "/workout-plan-exercises/{id}",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_WORKOUT_PLAN_EXERCISE_ID", required: true }],
      }),
      endpoint({
        id: "workout-logs.create",
        title: "Crear workout log",
        description: "Registro real de una sesion ejecutada.",
        method: "POST",
        path: "/workout-logs",
        auth: jwt,
        bodyTemplate: {
          workoutPlanId: "REEMPLAZAR_WORKOUT_PLAN_ID",
          logDate: "2026-06-01",
          totalDurationMinutes: 58,
          userRating: 8,
          aiRating: 0,
          notes: "Buen rendimiento general",
        },
      }),
      endpoint({
        id: "workout-logs.list",
        title: "Listar workout logs por fecha",
        description: "Consulta registros de una fecha puntual.",
        method: "GET",
        path: "/workout-logs",
        auth: jwt,
        queryTemplate: {
          date: "2026-06-01",
        },
      }),
      endpoint({
        id: "workout-logs.range",
        title: "Listar workout logs por rango",
        description: "Consulta historica de sesiones.",
        method: "GET",
        path: "/workout-logs/range",
        auth: jwt,
        queryTemplate: {
          startDate: "2026-05-26",
          endDate: "2026-06-01",
        },
      }),
      endpoint({
        id: "workout-logs.summary",
        title: "Resumen de workout logs",
        description: "Agregado total de sesiones y calificaciones.",
        method: "GET",
        path: "/workout-logs/summary",
        auth: jwt,
      }),
      endpoint({
        id: "workout-logs.get",
        title: "Obtener workout log por ID",
        description: "Detalle de sesion puntual.",
        method: "GET",
        path: "/workout-logs/{id}",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_WORKOUT_LOG_ID", required: true }],
      }),
      endpoint({
        id: "workout-logs.patch",
        title: "Actualizar workout log",
        description: "Corrige duracion, notas o rating.",
        method: "PATCH",
        path: "/workout-logs/{id}",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_WORKOUT_LOG_ID", required: true }],
        bodyTemplate: {
          workoutPlanId: "REEMPLAZAR_WORKOUT_PLAN_ID",
          logDate: "2026-06-01",
          totalDurationMinutes: 62,
          userRating: 9,
          aiRating: 0,
          notes: "Mejor sesion de la semana",
        },
      }),
      endpoint({
        id: "workout-logs.delete",
        title: "Eliminar workout log",
        description: "Borra una sesion registrada.",
        method: "DELETE",
        path: "/workout-logs/{id}",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_WORKOUT_LOG_ID", required: true }],
      }),
      endpoint({
        id: "workout-logs.exercises.create",
        title: "Agregar ejercicio a workout log",
        description: "Registra el resultado de un ejercicio dentro de la sesion.",
        method: "POST",
        path: "/workout-logs/{id}/exercises",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_WORKOUT_LOG_ID", required: true }],
        bodyTemplate: {
          exerciseId: "REEMPLAZAR_EXERCISE_ID",
          setsDone: 4,
          repsDone: "8,8,7,7",
          weightKg: 22.5,
          durationSeconds: 70,
          aiRecommendedDurationSeconds: 60,
          aiScore: 0,
          userNotes: "Ultimas series muy demandantes",
        },
      }),
      endpoint({
        id: "workout-log-exercises.patch",
        title: "Actualizar ejercicio de workout log",
        description: "Edita una linea de ejecucion ya guardada.",
        method: "PATCH",
        path: "/workout-log-exercises/{id}",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_WORKOUT_LOG_EXERCISE_ID", required: true }],
        bodyTemplate: {
          exerciseId: "REEMPLAZAR_EXERCISE_ID",
          setsDone: 5,
          repsDone: "8,8,8,7,6",
          weightKg: 22.5,
          durationSeconds: 75,
          aiRecommendedDurationSeconds: 60,
          aiScore: 0,
          userNotes: "Se agrego una serie extra",
        },
      }),
      endpoint({
        id: "workout-log-exercises.delete",
        title: "Eliminar ejercicio de workout log",
        description: "Borra la linea de ejecucion del log.",
        method: "DELETE",
        path: "/workout-log-exercises/{id}",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_WORKOUT_LOG_EXERCISE_ID", required: true }],
      }),
    ],
  },
  {
    id: "ai",
    title: "8. IA",
    description: "Deja estos endpoints al final porque suelen depender del contexto previo del usuario y sus datos.",
    endpoints: [
      endpoint({
        id: "ai.estimate-calories",
        title: "Estimar calorias",
        description: "Prompt libre para calculo aproximado.",
        method: "POST",
        path: "/ai/estimate-calories",
        auth: jwt,
        bodyTemplate: {
          prompt: "200g pechuga de pollo con 150g arroz integral y verduras salteadas",
        },
      }),
      endpoint({
        id: "ai.generate-meal-plan",
        title: "Generar meal plan con IA",
        description: "Input libre encapsulado en `input`.",
        method: "POST",
        path: "/ai/generate-meal-plan",
        auth: jwt,
        bodyTemplate: {
          input: {
            goal: "fat_loss",
            calories: 2100,
            trainingDays: 4,
            preferences: ["pollo", "arroz", "huevo"],
          },
        },
      }),
      endpoint({
        id: "ai.generate-workout-plan",
        title: "Generar workout plan con IA",
        description: "Input libre para sugerencia de rutina.",
        method: "POST",
        path: "/ai/generate-workout-plan",
        auth: jwt,
        bodyTemplate: {
          input: {
            goal: "gain_muscle",
            daysPerWeek: 4,
            equipment: ["dumbbells", "bench"],
            injuries: [],
          },
        },
      }),
      endpoint({
        id: "ai.recommend-recipes",
        title: "Recomendar recetas con IA",
        description: "Sugiere recetas segun objetivos y preferencias.",
        method: "POST",
        path: "/ai/recommend-recipes",
        auth: jwt,
        bodyTemplate: {
          input: {
            goal: "maintenance",
            availableFoods: ["avena", "yogur", "frutos rojos"],
            avoid: ["cacahuate"],
          },
        },
      }),
      endpoint({
        id: "ai.analyze-progress",
        title: "Analizar progreso con IA",
        description: "Evalua un resumen de avance usando el motor IA.",
        method: "POST",
        path: "/ai/analyze-progress",
        auth: jwt,
        bodyTemplate: {
          input: {
            weightTrend: [68.5, 68.2, 67.9],
            adherence: 0.86,
            workoutConsistency: 0.9,
            notes: "Buen cumplimiento semanal",
          },
        },
      }),
      endpoint({
        id: "ai.history",
        title: "Listar historial IA",
        description: "Historial de solicitudes del usuario.",
        method: "GET",
        path: "/ai/history",
        auth: jwt,
      }),
      endpoint({
        id: "ai.history.get",
        title: "Obtener historial IA por ID",
        description: "Detalle de una ejecucion puntual.",
        method: "GET",
        path: "/ai/history/{id}",
        auth: jwt,
        pathParams: [{ name: "id", value: "REEMPLAZAR_AI_REQUEST_ID", required: true }],
      }),
    ],
  },
];
