### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### Obtener todas las comidas
GET http://localhost:8080/api/food

###
DELETE http://localhost:8080/api/food/

### Obtener comida por id
GET http://localhost:8080/api/food/1

### Crear una nueva comida
POST http://localhost:8080/api/food
Content-Type: application/json

{
  "country": "México",
  "category": "Legumbre",
  "name": "Lentejas",
  "quantity": 100,
  "unit": 1,
  "calories": 116,
  "protein": 9,
  "carb": 20,
  "fat": 0.4,
  "sugar": 1.8,
  "sodium": 2
}

### Solicitudes para recetas
GET http://localhost:8080/api/recipes


### Obtener receta por id
GET http://localhost:8080/api/recipes/7


### Crear una nueva receta
POST http://localhost:8080/api/recipes
Content-Type: application/json

{
"name": "Ensalada 3",
"description": "Una ensalada fresca con verduras variadas.",
"instructions": "Mezclar todos los ingredientes en un bol y agregar aderezo al gusto.",
"ingredientIds": [4, 6],
"idUser": 1
}


### Borrar recetas
DELETE http://localhost:8080/api/recipes/8

### Solicitudes para usuarios
GET http://localhost:8080/api/users/